# Generated by Django 5.1.3 on 2025-04-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
