# Generated by Django 5.1.3 on 2025-04-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notification_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='n_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
