# Generated by Django 5.1.3 on 2025-03-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_blogcategory_blogcomment_blogpost_blogcomment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
