# Generated by Django 5.1.3 on 2025-03-31 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_blogpost_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
