# Generated by Django 5.1.3 on 2025-03-31 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_user_blogcomment_author_remove_blogpost_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
