# Generated by Django 5.1.3 on 2025-04-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_blogpost_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
