# Generated by Django 5.1.3 on 2025-04-03 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_blogcomment_email_blogcomment_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='blog',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='bloggpost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='shop.blogpost'),
        ),
    ]
