# Generated by Django 5.1.3 on 2025-04-03 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_blogcomment_blog_blogcomment_bloggpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='bloggpost',
            new_name='post',
        ),
    ]
