# Generated by Django 5.1.3 on 2025-04-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_shopcategory_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcategory',
            name='categoryID',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
