# Generated by Django 5.1.3 on 2025-04-26 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konnekt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='convID',
            new_name='conv_id',
        ),
    ]
