# Generated by Django 5.1.3 on 2025-04-27 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnekt', '0002_rename_convid_conversation_conv_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conv_id',
            field=models.CharField(editable=False, max_length=8, unique=True),
        ),
    ]
