# Generated by Django 5.1.3 on 2025-04-27 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konnekt', '0003_alter_conversation_conv_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='conversationitem',
            options={'ordering': ['-timestamp']},
        ),
    ]
