# Generated by Django 5.1.3 on 2025-04-27 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konnekt', '0004_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationitem',
            options={'ordering': ['timestamp']},
        ),
    ]
