# Generated by Django 5.1.3 on 2025-04-30 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0026_profile_bio_profile_facebook_profile_full_name_and_more'),
        ('konnekt', '0006_note_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='dash.profile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='dash.profile')),
            ],
            options={
                'unique_together': {('owner', 'contact')},
            },
        ),
    ]
