# Generated by Django 5.1.3 on 2025-05-01 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnekt', '0011_alter_userstatus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='last_ping',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
