# Generated by Django 5.1.3 on 2025-05-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnekt', '0013_conversationreadstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationreadstatus',
            name='last_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
