# Generated by Django 5.1.3 on 2025-05-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnekt', '0014_alter_conversationreadstatus_last_read_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationitem',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
