# Generated by Django 5.1.3 on 2025-05-05 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnekt', '0017_messageimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageimage',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='konnekt.conversationitem'),
        ),
    ]
