# Generated by Django 5.1.3 on 2025-05-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnekt', '0018_alter_messageimage_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageimage',
            name='msgID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
