# Generated by Django 5.1.3 on 2025-05-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konnekt', '0020_pushsubscription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pushsubscription',
            options={'verbose_name': 'Push Subscription', 'verbose_name_plural': 'Push Subscriptions'},
        ),
        migrations.RemoveField(
            model_name='pushsubscription',
            name='subscription_data',
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='endpoint',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pushsubscription',
            name='keys',
            field=models.JSONField(null=True),
        ),
    ]
