# Generated by Django 5.1.3 on 2025-03-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0007_alter_delivery_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
