# Generated by Django 5.1.3 on 2025-03-22 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0008_remove_transaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
