# Generated by Django 5.1.3 on 2025-03-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0010_delivery_is_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaysdeal',
            name='time',
        ),
        migrations.AddField(
            model_name='todaysdeal',
            name='duration',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
