# Generated by Django 5.1.3 on 2025-03-31 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0011_remove_todaysdeal_time_todaysdeal_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaysdeal',
            name='duration',
        ),
        migrations.AddField(
            model_name='todaysdeal',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
