# Generated by Django 5.1.3 on 2025-04-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0013_remove_todaysdeal_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaysdeal',
            name='price',
        ),
        migrations.RemoveField(
            model_name='todaysdeal',
            name='status',
        ),
        migrations.AddField(
            model_name='todaysdeal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
