# Generated by Django 5.1.3 on 2025-04-03 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0014_remove_todaysdeal_price_remove_todaysdeal_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_featured',
            new_name='is_admin',
        ),
    ]
