# Generated by Django 5.1.3 on 2025-04-03 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0015_rename_is_featured_profile_is_admin'),
        ('shop', '0014_rename_bloggpost_blogcomment_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
    ]
