# Generated by Django 5.1.3 on 2025-04-05 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0016_rename_units_unit'),
        ('shop', '0016_alter_shopcategory_categoryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.CharField(max_length=40, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop')),
            ],
        ),
    ]
