# Generated by Django 5.1.3 on 2025-04-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0017_homepagesession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagesession',
            old_name='timestamp',
            new_name='entry_time',
        ),
        migrations.AddField(
            model_name='homepagesession',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
