# Generated by Django 5.1.3 on 2025-04-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0018_rename_timestamp_homepagesession_entry_time_and_more'),
        ('shop', '0016_alter_shopcategory_categoryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagesession',
            name='sessionID',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='homepagesession',
            unique_together={('shop', 'sessionID')},
        ),
    ]
