# Generated by Django 5.1.3 on 2025-04-05 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0019_alter_homepagesession_sessionid_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homepagesession',
            unique_together=set(),
        ),
    ]
