# Generated by Django 5.1.3 on 2025-04-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0020_alter_homepagesession_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
