# Generated by Django 5.1.3 on 2025-04-09 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0021_profile_total_spent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='del_product', to='dash.inventory'),
        ),
    ]
