# Generated by Django 5.1.3 on 2025-04-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0022_alter_deliveryitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
