# Generated by Django 5.1.3 on 2025-04-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0023_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
