# Generated by Django 5.1.3 on 2025-05-01 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0026_profile_bio_profile_facebook_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 1, 0, 23, 29, 532588, tzinfo=datetime.timezone.utc)),
        ),
    ]
