# Generated by Django 5.1.3 on 2025-05-01 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0028_alter_profile_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_online',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_seen',
        ),
    ]
