# Generated by Django 5.1.3 on 2025-05-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0029_remove_profile_is_online_remove_profile_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='access_level',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
