# Generated by Django 5.1.3 on 2025-05-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0031_profile_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='access_level',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
